# File generated by running OpenTofu, not meant to be manually edited
all:
  children:
%{ for hv_name, hv in hypervisors ~}
    ${hv_name}:
      children:
        ${hv_name}_lxc:
          hosts:
%{ for host in hv.lxc ~}
            ${host.name}:
              ansible_host: ${host.ip}
              vmid: ${host.vmid}
%{ endfor ~}
        ${hv_name}_vm:
          hosts:
%{ for host in hv.vm ~}
            ${host.name}:
              ansible_host: ${host.ip}
              vmid: ${host.vmid}
%{ endfor ~}
%{ endfor ~}

    lxc:
      children:
%{ for hv_name, _ in hypervisors ~}
        ${hv_name}_lxc:
%{ endfor ~}

    vm:
      children:
%{ for hv_name, _ in hypervisors ~}
        ${hv_name}_vm:
%{ endfor ~}

%{ for tag, hosts in tag_groups ~}
    ${tag}:
      hosts:
%{ for host in hosts ~}
        ${host.name}:
          ansible_host: ${host.ip}
          vmid: ${host.vmid}
%{ endfor ~}
%{ endfor ~}

  vars:
    ansible_user: "${ansible_user}"
    ansible_ssh_private_key_file: "${ansible_ssh_private_key_file}"
